version: '3'

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ghbdtnbr
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:  
      - ./postgre_data:/var/lib/postgresql/data


  app: 
    container_name: go-api 
    build:
      context: .
      dockerfile: Api.Dockerfile
    image: go-api  
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    

  reverse:
    image: nginx:1.17.10
    container_name: reverse_proxy
    ports:
      - "80:80"

    volumes: 
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    links: 
      - app